[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_migrator = "gr8tD6dY1HrJrxzoGKUWCvATpN2qTX2E3HBcPKuGY77"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"
initialize = "yarn run ts-node scripts/initialize.ts"
migrate = "yarn run ts-node scripts/migrate.ts"

[workspace.metadata]
solana-version = "2.2.21"  

[[workspace.metadata.verifiable]]
program = "token_migrator"