name: Deploy token-migrator

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Target network"
        required: true
        type: choice
        options: [mainnet, devnet]
        default: "mainnet"
      priority-fee:
        description: "Priority fee (microlamports)"
        required: true
        default: "300000"
        type: string

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "token_migrator"
      override-program-id: "gr8tqq2ripsM6N46gLWpSDXtdrH6J9jaXoyya1ELC9t"
      network: ${{ inputs.network }}
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "mainnet"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      DEVNET_MULTISIG: ${{ secrets.DEVNET_MULTISIG }}
      DEVNET_MULTISIG_VAULT: ${{ secrets.DEVNET_MULTISIG_VAULT }}
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
