name: generate-verifiable-builds
on:
 workflow_dispatch:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
 generate-verifiable-token-migrator:
   runs-on: ubuntu-22.04
   steps:
     - uses: actions/checkout@v4
     
     - name: Install system dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y libudev-dev pkg-config
     
     - uses: metadaoproject/anchor-verifiable-build@v0.5
       with:
         program: token-migrator
         anchor-version: '0.31.1'
         solana-cli-version: '2.3.0'
         features: 'production' 
     - run: 'git pull --rebase'
     - run: cp target/deploy/token-migrator.so ./verifiable-builds
     - name: Commit verifiable build back to mainline
       uses: EndBug/add-and-commit@v9.1.4
       with:
         default_author: github_actions
         message: 'Update token-migrator verifiable build'